[JD] Loading enabled option
mistic100/Photo-Sphere-Viewer pull request #1124
Opened 2023-10-19 04:02 UTC by imjfdeviar

**Merge request checklist**

-   [ x] All lints and tests pass. If needed, new unit tests were added.
-   [ ] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.

## Needed changes in documentation:

#### `loadingEnabled`

-   type: `boolean`

Prevent to show loading

2023-10-19 08:02 UTC, mistic100 commented
You can already call `setPanorama` with option `showLoader: false`, there is no need for an option.

Plus I don't like the fact it totally disables the component, it might be called in other contexts.

2023-10-19 13:12 UTC, imjfdeviar commented
I get it, I didn't see the option in setPanorama, I like the way it is implemented but I was using some plugins: `VirtualTour` and it does not have the option in `VirtualTourTransitionOptions`.

Im using a custom loading with the events: `panorama-loaded` and `load-progress` and I dont want to see the loader in general (Because of that I added this option in general features to disable it from a general way). I'll update this PR updating transition options for the tour plugin.

BTW, I would like to contribute with this Repo, I would like to learn, with your experience, how to archive this goal? or where to add this feature?

2023-10-21 08:49 UTC, mistic100 commented
Adding an option to VirtualTourPlugin is a good solution.

The documentation is in the same repo https://github.com/mistic100/Photo-Sphere-Viewer/blob/main/docs/plugins/virtual-tour.md you can update it yourself

2023-10-21 08:49 UTC, mistic100 requested changes

2023-10-21 08:49 UTC, mistic100 commented on packages/virtual-tour-plugin/src/VirtualTourPlugin.ts
> +                if(transitionOptions.showLoader)
please respect the code style

2023-10-26 17:26 UTC, closed without merging