chore: className for compass plugin
mistic100/Photo-Sphere-Viewer pull request #1150
Opened 2023-11-17 06:19 UTC by venmax

**Merge request checklist**

-   [x] All lints and tests pass. If needed, new unit tests were added.
-   [ ] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.

ClassName for compass. for example `position: [string, string]` may not ehough for positioning

2023-11-17 16:04 UTC, mistic100 commented
Please add a comment on the property and update the documentation

2023-11-18 10:48 UTC, mistic100 requested changes

2023-11-18 10:48 UTC, mistic100 commented on packages/compass-plugin/src/CompassPlugin.ts
> +        className: ''
```suggestion
        className: null,
```

2023-11-20 01:26 UTC, venmax commented
> Please add a comment on the property and update the documentation

done

2023-11-20 11:55 UTC, mistic100 requested changes

2023-11-20 11:55 UTC, mistic100 commented on docs/plugins/compass.md
> +-   type: `string`
```suggestion
-   type: `string`
-   updatable: yes
```

2023-11-20 17:20 UTC, merged