feat:gyroscope add moveMode option
mistic100/Photo-Sphere-Viewer pull request #695
Opened 2022-06-12 07:46 UTC by Cansiny0320

**Merge request checklist**

- [x] I read the [guidelines for contributing](https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/.github/CONTRIBUTING.md)
- [x] I created my branch from `dev` and I am issuing the PR to `dev`
- [x] Unit tests are OK

2022-06-12 07:51 UTC, Cansiny0320 commented
close #693

2022-06-14 11:15 UTC, mistic100 requested changes
Missing the change in "types"

2022-06-14 11:15 UTC, mistic100 commented on docs/plugins/plugin-gyroscope.md
> +move smooth or fast
```suggestion
How the gyroscope data is used to rotate the panorama.
```

2022-06-14 11:15 UTC, mistic100 commented on src/plugins/gyroscope/index.js
> + * @property {'smooth' | 'fast'} [moveMode='smooth'] - move smooth or fast
```suggestion
 * @property {'smooth' | 'fast'} [moveMode='smooth'] - How the gyroscope data is used to rotate the panorama
```

2022-06-15 11:41 UTC, Cansiny0320 commented
What else needs to be modified? @mistic100

2022-06-15 11:54 UTC, mistic100 commented
> What else needs to be modified? @mistic100

my previous comment https://github.com/mistic100/Photo-Sphere-Viewer/pull/695#pullrequestreview-1005676245

2022-06-15 13:09 UTC, Cansiny0320 commented
> 
Maybe I understand the wrong, do I want me to modify the explanation of the type? I have modified it

2022-06-15 13:10 UTC, Cansiny0320 commented
> > What else needs to be modified? @mistic100
> 
> my previous comment [#695 (review)](https://github.com/mistic100/Photo-Sphere-Viewer/pull/695#pullrequestreview-1005676245)

Maybe I understand the wrong, do I want me to modify the explanation of the type? I have modified it

2022-06-15 13:12 UTC, Cansiny0320 commented
> types

oh,i got it

2022-06-15 13:12 UTC, Cansiny0320 commented
> > What else needs to be modified? @mistic100
> 
> my previous comment [#695 (review)](https://github.com/mistic100/Photo-Sphere-Viewer/pull/695#pullrequestreview-1005676245)

oh,i got it

2022-06-15 13:23 UTC, merged